package comparator.enums;

public enum UniversityComparatorsEnum {
    UNIVERSITY_ID,
    UNIVERSITY_FULL_NAME,
    UNIVERSITY_SHORT_NAME,
    UNIVERSITY_YEAR_OF_FOUNDATION,
    UNIVERSITY_MAIN_PROFILE,
    UNIVERSITY_LOCATION,
    CLEAR;
}
